#!/usr/bin/python
import os
from datetime import datetime
import shutil

import switch

switch.switch(True)

now = datetime.now()
timestamp = '_'.join(str(now).split()).rsplit('.', 1)[0].replace(':', '-')
path = 'decrypted/{}.txt'.format(timestamp)
with open(path, 'w') as f:
  f.write('')
os.system('open {}'.format(path))
switch.switch(False)
shutil.rmtree('decrypted')
